### ISSUE TITLE
Add a profile component that will display user's details

### ISSUE THREAD

**Issue by HristovCodes** [HristovCodes/Events-Board#1]
Currently the user's details are being displayed inside his feed which is not the correct place for that.

To Do:
1. Make a new component and move them to there. 
2. Link it to the sidebar.
3. Add it to the router in the Home component.
3. Style it accordingly.

Extra:
1. Add an option to update the email/password (change them).
2. Add an option to update the profile picture (also needs to be displayed in the sidebar)

**Comment by guyus15** [comment]
Hi, I'd like to be assigned to this issue

**Comment by HristovCodes** [comment]
> Hi, I'd like to be assigned to this issue

There's already a pull request for this issue by @Bozhidar-A. If he doesn't finish it you can. I'll ping you and let you know later today if you can start working on it.
